const LANGUAGE_CODES = {
  eng: 'English',
  por: 'Portuguese',
  spa: 'Spanish',
  fre: 'French',
  ger: 'German',
  ita: 'Italian',
  rus: 'Russian',
  chi: 'Chinese',
  jpn: 'Japanese',
  kor: 'Korean',
  ara: 'Arabic',
  hin: 'Hindi',
  tur: 'Turkish',
  pol: 'Polish',
  dut: 'Dutch',
  swe: 'Swedish',
  nor: 'Norwegian',
  dan: 'Danish',
  fin: 'Finnish',
  cze: 'Czech',
  hun: 'Hungarian',
  rum: 'Romanian',
  gre: 'Greek',
  heb: 'Hebrew',
  tha: 'Thai',
  vie: 'Vietnamese',
  ind: 'Indonesian',
  ukr: 'Ukrainian',
  cat: 'Catalan',
  per: 'Persian',
  ben: 'Bengali',
  tam: 'Tamil',
  urd: 'Urdu',
  lat: 'Latin',
  wel: 'Welsh',
  gle: 'Irish',
  bul: 'Bulgarian',
  hrv: 'Croatian',
  srp: 'Serbian',
  slv: 'Slovenian',
  slo: 'Slovak',
  lit: 'Lithuanian',
  lav: 'Latvian',
  est: 'Estonian',
  geo: 'Georgian',
  arm: 'Armenian',
  mal: 'Malay',
  tgl: 'Tagalog',
  swa: 'Swahili',
  afr: 'Afrikaans',
};

const CODE_TO_REST_COUNTRIES = {
  eng: 'english',
  por: 'portuguese',
  spa: 'spanish',
  fre: 'french',
  ger: 'german',
  ita: 'italian',
  rus: 'russian',
  chi: 'chinese',
  jpn: 'japanese',
  kor: 'korean',
  ara: 'arabic',
  hin: 'hindi',
  tur: 'turkish',
  pol: 'polish',
  dut: 'dutch',
  swe: 'swedish',
  nor: 'norwegian',
  dan: 'danish',
  fin: 'finnish',
  cze: 'czech',
  hun: 'hungarian',
  rum: 'romanian',
  gre: 'greek',
  heb: 'hebrew',
  tha: 'thai',
  vie: 'vietnamese',
  ind: 'indonesian',
  ukr: 'ukrainian',
  cat: 'catalan',
  per: 'persian',
  ben: 'bengali',
  tam: 'tamil',
  urd: 'urdu',
  lat: 'latin',
  wel: 'welsh',
  gle: 'irish',
  bul: 'bulgarian',
  hrv: 'croatian',
  srp: 'serbian',
  slv: 'slovenian',
  slo: 'slovak',
  lit: 'lithuanian',
  lav: 'latvian',
  est: 'estonian',
  geo: 'georgian',
  arm: 'armenian',
  mal: 'malay',
  tgl: 'tagalog',
  swa: 'swahili',
  afr: 'afrikaans',
};

export function getLanguageName(code) {
  return LANGUAGE_CODES[code] || code;
}

export function getRestCountriesLanguage(code) {
  return CODE_TO_REST_COUNTRIES[code] || null;
}
